version: 2

models:

    - name: sales
      description : >
        test
        test2
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: PK - identifier of the orders
            tests : 
            - not_null 

          - name: products_id
            description: PK - identifier of the product
            tests : 
            - not_null 

          - name: qty

          - name: turnover
            description: sales
            tests : 
            - not_null

          - name: purchase_cost
            description: sales
            tests : 
            - not_null

          - name: margin
            description: sales